//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.26 at 11:37:41 AM CET 
//


package eu.fbk.das.process.engine.api.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for dpChangeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="dpChangeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="dpName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="eventName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dpChangeType")
public class DpChangeType {

    @XmlAttribute(name = "dpName")
    protected String dpName;
    @XmlAttribute(name = "eventName")
    protected String eventName;

    /**
     * Gets the value of the dpName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDpName() {
        return dpName;
    }

    /**
     * Sets the value of the dpName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDpName(String value) {
        this.dpName = value;
    }

    /**
     * Gets the value of the eventName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEventName() {
        return eventName;
    }

    /**
     * Sets the value of the eventName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEventName(String value) {
        this.eventName = value;
    }

}
