<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:process xmlns:ns2="http://docs.oasis-open.org/wsbpel/2.0/process/executable">
    <ns2:sequence>
        <ns2:invoke>
            <name>BS_RegistrationRequest</name>
            <order>0</order>
        </ns2:invoke>
        <ns2:invoke>
            <name>FC_RegistrationRequest</name>
            <order>1</order>
        </ns2:invoke>
        <ns2:reply>
            <name>FC_RegistrationAck</name>
            <order>2</order>
        </ns2:reply>
        <ns2:invoke>
            <name>TC_RegistrationRequest</name>
            <order>3</order>
        </ns2:invoke>
        <ns2:reply>
            <name>TC_RegistrationAck</name>
            <order>4</order>
        </ns2:reply>
        <ns2:invoke>
            <name>TC_TrainBookingRequest</name>
            <order>5</order>
        </ns2:invoke>
        <ns2:invoke>
            <name>FC_FlexibusBookingRequest</name>
            <order>6</order>
        </ns2:invoke>
        <ns2:reply>
            <name>FC_BookingResult</name>
            <order>7</order>
        </ns2:reply>
        <ns2:reply xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="processActivity">
            <name>FC_ConfirmAndPay</name>
            <order>8</order>
        </ns2:reply>
        <ns2:reply xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="processActivity">
            <name>TC_PayTicket</name>
            <order>9</order>
        </ns2:reply>
        <ns2:reply>
            <name>TC_BookingResult</name>
            <order>10</order>
        </ns2:reply>
        <ns2:invoke>
            <name>CS_MembershipRequest</name>
            <order>11</order>
        </ns2:invoke>
        <ns2:reply xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="processActivity">
            <name>CS_UpdateSmartMobilityCard</name>
            <order>12</order>
        </ns2:reply>
        <ns2:reply>
            <name>CS_MembershipReply</name>
            <order>13</order>
        </ns2:reply>
        <ns2:invoke>
            <name>CS_CarReservationRequest</name>
            <order>14</order>
        </ns2:invoke>
        <ns2:reply>
            <name>CS_CarReservationDetails</name>
            <order>15</order>
        </ns2:reply>
        <ns2:invoke>
            <name>CS_DetailsAssessed</name>
            <order>16</order>
        </ns2:invoke>
        <ns2:reply>
            <name>CS_CarReservationReply</name>
            <order>17</order>
        </ns2:reply>
        <ns2:reply xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="processActivity">
            <name>BS_UpdateSmartMobilityCard</name>
            <order>18</order>
        </ns2:reply>
        <ns2:reply>
            <name>BS_RegistrationAck</name>
            <order>19</order>
        </ns2:reply>
    </ns2:sequence>
</ns2:process>
