//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.31 at 04:38:35 PM CEST 
//


package eu.fbk.das.process.engine.api.jaxb.scenario;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eu.fbk.das.process.engine.api.jaxb.scenario package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.fbk.das.process.engine.api.jaxb.scenario
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Scenario }
     * 
     */
    public Scenario createScenario() {
        return new Scenario();
    }

    /**
     * Create an instance of {@link Scenario.DomainObject }
     * 
     */
    public Scenario.DomainObject createScenarioDomainObject() {
        return new Scenario.DomainObject();
    }

    /**
     * Create an instance of {@link Scenario.DomainObject.DomainObjectInstance }
     * 
     */
    public Scenario.DomainObject.DomainObjectInstance createScenarioDomainObjectDomainObjectInstance() {
        return new Scenario.DomainObject.DomainObjectInstance();
    }

    /**
     * Create an instance of {@link Scenario.DomainObject.DomainObjectInstance.DomainObjectInstanceKnowledge }
     * 
     */
    public Scenario.DomainObject.DomainObjectInstance.DomainObjectInstanceKnowledge createScenarioDomainObjectDomainObjectInstanceDomainObjectInstanceKnowledge() {
        return new Scenario.DomainObject.DomainObjectInstance.DomainObjectInstanceKnowledge();
    }

    /**
     * Create an instance of {@link Scenario.DomainObject.DomainObjectInstance.Process }
     * 
     */
    public Scenario.DomainObject.DomainObjectInstance.Process createScenarioDomainObjectDomainObjectInstanceProcess() {
        return new Scenario.DomainObject.DomainObjectInstance.Process();
    }

    /**
     * Create an instance of {@link Scenario.DomainObject.DomainObjectInstance.DomainObjectInstanceKnowledge.Dp }
     * 
     */
    public Scenario.DomainObject.DomainObjectInstance.DomainObjectInstanceKnowledge.Dp createScenarioDomainObjectDomainObjectInstanceDomainObjectInstanceKnowledgeDp() {
        return new Scenario.DomainObject.DomainObjectInstance.DomainObjectInstanceKnowledge.Dp();
    }

}
