//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.07 at 05:12:50 PM CET 
//


package eu.fbk.das.process.engine.api.jaxb.scenario;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded">
 *         &lt;element name="domainObject">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="domainObjectInstance">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="domainObjectInstanceKnowledge">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="dp" maxOccurs="unbounded" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;simpleContent>
 *                                             &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                               &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                               &lt;attribute name="currentState" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                             &lt;/extension>
 *                                           &lt;/simpleContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="process">
 *                               &lt;complexType>
 *                                 &lt;simpleContent>
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                     &lt;attribute name="curentActivity" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/extension>
 *                                 &lt;/simpleContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="lat" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="long" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="preferenceFile" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="onTurn" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="hoaaVar" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="hoaa" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="ensemble" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="correlations" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="selectedRoute" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="pickupPoint" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="routes" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="file" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "domainObject"
})
@XmlRootElement(name = "scenario")
public class Scenario {

    @XmlElement(required = true)
    protected List<Scenario.DomainObject> domainObject;

    /**
     * Gets the value of the domainObject property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the domainObject property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDomainObject().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Scenario.DomainObject }
     * 
     * 
     */
    public List<Scenario.DomainObject> getDomainObject() {
        if (domainObject == null) {
            domainObject = new ArrayList<Scenario.DomainObject>();
        }
        return this.domainObject;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="domainObjectInstance">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="domainObjectInstanceKnowledge">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="dp" maxOccurs="unbounded" minOccurs="0">
     *                               &lt;complexType>
     *                                 &lt;simpleContent>
     *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                                     &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                     &lt;attribute name="currentState" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                   &lt;/extension>
     *                                 &lt;/simpleContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="process">
     *                     &lt;complexType>
     *                       &lt;simpleContent>
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                           &lt;attribute name="curentActivity" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/extension>
     *                       &lt;/simpleContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="lat" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="long" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="preferenceFile" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="onTurn" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="hoaaVar" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="hoaa" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="ensemble" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="correlations" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="selectedRoute" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="pickupPoint" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="routes" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="file" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "domainObjectInstance"
    })
    public static class DomainObject {

        protected List<Scenario.DomainObject.DomainObjectInstance> domainObjectInstance;
        @XmlAttribute(name = "file")
        protected String file;

        /**
         * Gets the value of the domainObjectInstance property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the domainObjectInstance property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDomainObjectInstance().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Scenario.DomainObject.DomainObjectInstance }
         * 
         * 
         */
        public List<Scenario.DomainObject.DomainObjectInstance> getDomainObjectInstance() {
            if (domainObjectInstance == null) {
                domainObjectInstance = new ArrayList<Scenario.DomainObject.DomainObjectInstance>();
            }
            return this.domainObjectInstance;
        }

        /**
         * Gets the value of the file property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFile() {
            return file;
        }

        /**
         * Sets the value of the file property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFile(String value) {
            this.file = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="domainObjectInstanceKnowledge">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="dp" maxOccurs="unbounded" minOccurs="0">
         *                     &lt;complexType>
         *                       &lt;simpleContent>
         *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                           &lt;attribute name="currentState" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                         &lt;/extension>
         *                       &lt;/simpleContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="process">
         *           &lt;complexType>
         *             &lt;simpleContent>
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                 &lt;attribute name="curentActivity" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/extension>
         *             &lt;/simpleContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="lat" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="long" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="preferenceFile" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="onTurn" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="hoaaVar" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="hoaa" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="ensemble" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="correlations" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="selectedRoute" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="pickupPoint" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="routes" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "domainObjectInstanceKnowledge",
            "process"
        })
        public static class DomainObjectInstance {

            @XmlElement(required = true)
            protected Scenario.DomainObject.DomainObjectInstance.DomainObjectInstanceKnowledge domainObjectInstanceKnowledge;
            @XmlElement(required = true)
            protected Scenario.DomainObject.DomainObjectInstance.Process process;
            @XmlAttribute(name = "id")
            protected String id;
            @XmlAttribute(name = "lat")
            protected String lat;
            @XmlAttribute(name = "long")
            protected String _long;
            @XmlAttribute(name = "preferenceFile")
            protected String preferenceFile;
            @XmlAttribute(name = "onTurn")
            protected Integer onTurn;
            @XmlAttribute(name = "hoaaVar")
            protected String hoaaVar;
            @XmlAttribute(name = "hoaa")
            protected String hoaa;
            @XmlAttribute(name = "ensemble")
            protected String ensemble;
            @XmlAttribute(name = "correlations")
            protected String correlations;
            @XmlAttribute(name = "selectedRoute")
            protected String selectedRoute;
            @XmlAttribute(name = "pickupPoint")
            protected Integer pickupPoint;
            @XmlAttribute(name = "routes")
            protected String routes;

            /**
             * Gets the value of the domainObjectInstanceKnowledge property.
             * 
             * @return
             *     possible object is
             *     {@link Scenario.DomainObject.DomainObjectInstance.DomainObjectInstanceKnowledge }
             *     
             */
            public Scenario.DomainObject.DomainObjectInstance.DomainObjectInstanceKnowledge getDomainObjectInstanceKnowledge() {
                return domainObjectInstanceKnowledge;
            }

            /**
             * Sets the value of the domainObjectInstanceKnowledge property.
             * 
             * @param value
             *     allowed object is
             *     {@link Scenario.DomainObject.DomainObjectInstance.DomainObjectInstanceKnowledge }
             *     
             */
            public void setDomainObjectInstanceKnowledge(Scenario.DomainObject.DomainObjectInstance.DomainObjectInstanceKnowledge value) {
                this.domainObjectInstanceKnowledge = value;
            }

            /**
             * Gets the value of the process property.
             * 
             * @return
             *     possible object is
             *     {@link Scenario.DomainObject.DomainObjectInstance.Process }
             *     
             */
            public Scenario.DomainObject.DomainObjectInstance.Process getProcess() {
                return process;
            }

            /**
             * Sets the value of the process property.
             * 
             * @param value
             *     allowed object is
             *     {@link Scenario.DomainObject.DomainObjectInstance.Process }
             *     
             */
            public void setProcess(Scenario.DomainObject.DomainObjectInstance.Process value) {
                this.process = value;
            }

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setId(String value) {
                this.id = value;
            }

            /**
             * Gets the value of the lat property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLat() {
                return lat;
            }

            /**
             * Sets the value of the lat property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLat(String value) {
                this.lat = value;
            }

            /**
             * Gets the value of the long property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLong() {
                return _long;
            }

            /**
             * Sets the value of the long property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLong(String value) {
                this._long = value;
            }

            /**
             * Gets the value of the preferenceFile property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPreferenceFile() {
                return preferenceFile;
            }

            /**
             * Sets the value of the preferenceFile property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPreferenceFile(String value) {
                this.preferenceFile = value;
            }

            /**
             * Gets the value of the onTurn property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getOnTurn() {
                return onTurn;
            }

            /**
             * Sets the value of the onTurn property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setOnTurn(Integer value) {
                this.onTurn = value;
            }

            /**
             * Gets the value of the hoaaVar property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getHoaaVar() {
                return hoaaVar;
            }

            /**
             * Sets the value of the hoaaVar property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setHoaaVar(String value) {
                this.hoaaVar = value;
            }

            /**
             * Gets the value of the hoaa property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getHoaa() {
                return hoaa;
            }

            /**
             * Sets the value of the hoaa property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setHoaa(String value) {
                this.hoaa = value;
            }

            /**
             * Gets the value of the ensemble property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEnsemble() {
                return ensemble;
            }

            /**
             * Sets the value of the ensemble property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEnsemble(String value) {
                this.ensemble = value;
            }

            /**
             * Gets the value of the correlations property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCorrelations() {
                return correlations;
            }

            /**
             * Sets the value of the correlations property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCorrelations(String value) {
                this.correlations = value;
            }

            /**
             * Gets the value of the selectedRoute property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSelectedRoute() {
                return selectedRoute;
            }

            /**
             * Sets the value of the selectedRoute property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSelectedRoute(String value) {
                this.selectedRoute = value;
            }

            /**
             * Gets the value of the pickupPoint property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getPickupPoint() {
                return pickupPoint;
            }

            /**
             * Sets the value of the pickupPoint property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setPickupPoint(Integer value) {
                this.pickupPoint = value;
            }

            /**
             * Gets the value of the routes property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRoutes() {
                return routes;
            }

            /**
             * Sets the value of the routes property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRoutes(String value) {
                this.routes = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="dp" maxOccurs="unbounded" minOccurs="0">
             *           &lt;complexType>
             *             &lt;simpleContent>
             *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                 &lt;attribute name="currentState" type="{http://www.w3.org/2001/XMLSchema}string" />
             *               &lt;/extension>
             *             &lt;/simpleContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "dp"
            })
            public static class DomainObjectInstanceKnowledge {

                protected List<Scenario.DomainObject.DomainObjectInstance.DomainObjectInstanceKnowledge.Dp> dp;

                /**
                 * Gets the value of the dp property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the dp property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getDp().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link Scenario.DomainObject.DomainObjectInstance.DomainObjectInstanceKnowledge.Dp }
                 * 
                 * 
                 */
                public List<Scenario.DomainObject.DomainObjectInstance.DomainObjectInstanceKnowledge.Dp> getDp() {
                    if (dp == null) {
                        dp = new ArrayList<Scenario.DomainObject.DomainObjectInstance.DomainObjectInstanceKnowledge.Dp>();
                    }
                    return this.dp;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;simpleContent>
                 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
                 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *       &lt;attribute name="currentState" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *     &lt;/extension>
                 *   &lt;/simpleContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "value"
                })
                public static class Dp {

                    @XmlValue
                    protected String value;
                    @XmlAttribute(name = "name")
                    protected String name;
                    @XmlAttribute(name = "currentState")
                    protected String currentState;

                    /**
                     * Gets the value of the value property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getValue() {
                        return value;
                    }

                    /**
                     * Sets the value of the value property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setValue(String value) {
                        this.value = value;
                    }

                    /**
                     * Gets the value of the name property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getName() {
                        return name;
                    }

                    /**
                     * Sets the value of the name property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setName(String value) {
                        this.name = value;
                    }

                    /**
                     * Gets the value of the currentState property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getCurrentState() {
                        return currentState;
                    }

                    /**
                     * Sets the value of the currentState property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setCurrentState(String value) {
                        this.currentState = value;
                    }

                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;simpleContent>
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *       &lt;attribute name="curentActivity" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/extension>
             *   &lt;/simpleContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class Process {

                @XmlValue
                protected String value;
                @XmlAttribute(name = "curentActivity")
                protected String curentActivity;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the curentActivity property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCurentActivity() {
                    return curentActivity;
                }

                /**
                 * Sets the value of the curentActivity property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCurentActivity(String value) {
                    this.curentActivity = value;
                }

            }

        }

    }

}
