//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.23 at 01:16:59 PM CET 
//


package eu.fbk.das.process.engine.api.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for actionVariableTypeValues.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="actionVariableTypeValues">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="default"/>
 *     &lt;enumeration value="integer"/>
 *     &lt;enumeration value="string"/>
 *     &lt;enumeration value="date"/>
 *     &lt;enumeration value="double"/>
 *     &lt;enumeration value="boolean"/>
 *     &lt;enumeration value="time"/>
 *     &lt;enumeration value="arrayOfString"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "actionVariableTypeValues", namespace = "http://das.fbk.eu/DataType")
@XmlEnum
public enum ActionVariableTypeValues {

    @XmlEnumValue("default")
    DEFAULT("default"),
    @XmlEnumValue("integer")
    INTEGER("integer"),
    @XmlEnumValue("string")
    STRING("string"),
    @XmlEnumValue("date")
    DATE("date"),
    @XmlEnumValue("double")
    DOUBLE("double"),
    @XmlEnumValue("boolean")
    BOOLEAN("boolean"),
    @XmlEnumValue("time")
    TIME("time"),
    @XmlEnumValue("arrayOfString")
    ARRAY_OF_STRING("arrayOfString");
    private final String value;

    ActionVariableTypeValues(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ActionVariableTypeValues fromValue(String v) {
        for (ActionVariableTypeValues c: ActionVariableTypeValues.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
