//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.01 at 03:13:26 PM CEST 
//


package eu.fbk.das.process.engine.api.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="domainProperties">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="domainProperty" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="oid" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *                           &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="fragments">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="fragment" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="assignment" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="o_name" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *                                     &lt;attribute name="oid" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="sid" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *                           &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="constraints" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="constraint" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;extension base="{http://das.fbk.eu/Annotation}PreconditionType">
 *                           &lt;attribute name="oid" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *                           &lt;attribute name="event" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *                         &lt;/extension>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="synchronization" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="point" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="domainProperty" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" maxOccurs="unbounded"/>
 *                                     &lt;/sequence>
 *                                     &lt;attribute name="oid" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="priority" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="nextActions" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="action" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>NMTOKEN">
 *                           &lt;attribute name="sid" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="controlFlowRequirements" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="requirement" type="{http://das.fbk.eu/Composition}ControlFlowType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="runtime" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="domainProperties" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="domainProperty" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;simpleContent>
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>NMTOKEN">
 *                                     &lt;attribute name="oid" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *                                   &lt;/extension>
 *                                 &lt;/simpleContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="fragments" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="fragment" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;simpleContent>
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>NMTOKEN">
 *                                     &lt;attribute name="sid" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *                                   &lt;/extension>
 *                                 &lt;/simpleContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "domainProperties",
    "fragments",
    "constraints",
    "synchronization",
    "nextActions",
    "controlFlowRequirements",
    "runtime"
})
@XmlRootElement(name = "composition", namespace = "http://das.fbk.eu/Composition")
public class Composition {

    @XmlElement(namespace = "http://das.fbk.eu/Composition", required = true)
    protected Composition.DomainProperties domainProperties;
    @XmlElement(namespace = "http://das.fbk.eu/Composition", required = true)
    protected Composition.Fragments fragments;
    @XmlElement(namespace = "http://das.fbk.eu/Composition")
    protected Composition.Constraints constraints;
    @XmlElement(namespace = "http://das.fbk.eu/Composition")
    protected Composition.Synchronization synchronization;
    @XmlElement(namespace = "http://das.fbk.eu/Composition")
    protected Composition.NextActions nextActions;
    @XmlElement(namespace = "http://das.fbk.eu/Composition")
    protected Composition.ControlFlowRequirements controlFlowRequirements;
    @XmlElement(namespace = "http://das.fbk.eu/Composition")
    protected Composition.Runtime runtime;
    @XmlAttribute(name = "name")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String name;

    /**
     * Gets the value of the domainProperties property.
     * 
     * @return
     *     possible object is
     *     {@link Composition.DomainProperties }
     *     
     */
    public Composition.DomainProperties getDomainProperties() {
        return domainProperties;
    }

    /**
     * Sets the value of the domainProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link Composition.DomainProperties }
     *     
     */
    public void setDomainProperties(Composition.DomainProperties value) {
        this.domainProperties = value;
    }

    /**
     * Gets the value of the fragments property.
     * 
     * @return
     *     possible object is
     *     {@link Composition.Fragments }
     *     
     */
    public Composition.Fragments getFragments() {
        return fragments;
    }

    /**
     * Sets the value of the fragments property.
     * 
     * @param value
     *     allowed object is
     *     {@link Composition.Fragments }
     *     
     */
    public void setFragments(Composition.Fragments value) {
        this.fragments = value;
    }

    /**
     * Gets the value of the constraints property.
     * 
     * @return
     *     possible object is
     *     {@link Composition.Constraints }
     *     
     */
    public Composition.Constraints getConstraints() {
        return constraints;
    }

    /**
     * Sets the value of the constraints property.
     * 
     * @param value
     *     allowed object is
     *     {@link Composition.Constraints }
     *     
     */
    public void setConstraints(Composition.Constraints value) {
        this.constraints = value;
    }

    /**
     * Gets the value of the synchronization property.
     * 
     * @return
     *     possible object is
     *     {@link Composition.Synchronization }
     *     
     */
    public Composition.Synchronization getSynchronization() {
        return synchronization;
    }

    /**
     * Sets the value of the synchronization property.
     * 
     * @param value
     *     allowed object is
     *     {@link Composition.Synchronization }
     *     
     */
    public void setSynchronization(Composition.Synchronization value) {
        this.synchronization = value;
    }

    /**
     * Gets the value of the nextActions property.
     * 
     * @return
     *     possible object is
     *     {@link Composition.NextActions }
     *     
     */
    public Composition.NextActions getNextActions() {
        return nextActions;
    }

    /**
     * Sets the value of the nextActions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Composition.NextActions }
     *     
     */
    public void setNextActions(Composition.NextActions value) {
        this.nextActions = value;
    }

    /**
     * Gets the value of the controlFlowRequirements property.
     * 
     * @return
     *     possible object is
     *     {@link Composition.ControlFlowRequirements }
     *     
     */
    public Composition.ControlFlowRequirements getControlFlowRequirements() {
        return controlFlowRequirements;
    }

    /**
     * Sets the value of the controlFlowRequirements property.
     * 
     * @param value
     *     allowed object is
     *     {@link Composition.ControlFlowRequirements }
     *     
     */
    public void setControlFlowRequirements(Composition.ControlFlowRequirements value) {
        this.controlFlowRequirements = value;
    }

    /**
     * Gets the value of the runtime property.
     * 
     * @return
     *     possible object is
     *     {@link Composition.Runtime }
     *     
     */
    public Composition.Runtime getRuntime() {
        return runtime;
    }

    /**
     * Sets the value of the runtime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Composition.Runtime }
     *     
     */
    public void setRuntime(Composition.Runtime value) {
        this.runtime = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="constraint" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;extension base="{http://das.fbk.eu/Annotation}PreconditionType">
     *                 &lt;attribute name="oid" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
     *                 &lt;attribute name="event" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
     *               &lt;/extension>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "constraint"
    })
    public static class Constraints {

        @XmlElement(namespace = "http://das.fbk.eu/Composition", required = true)
        protected List<Composition.Constraints.Constraint> constraint;

        /**
         * Gets the value of the constraint property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the constraint property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getConstraint().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Composition.Constraints.Constraint }
         * 
         * 
         */
        public List<Composition.Constraints.Constraint> getConstraint() {
            if (constraint == null) {
                constraint = new ArrayList<Composition.Constraints.Constraint>();
            }
            return this.constraint;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;extension base="{http://das.fbk.eu/Annotation}PreconditionType">
         *       &lt;attribute name="oid" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
         *       &lt;attribute name="event" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
         *     &lt;/extension>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Constraint
            extends PreconditionType
        {

            @XmlAttribute(name = "oid", required = true)
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlSchemaType(name = "NMTOKEN")
            protected String oid;
            @XmlAttribute(name = "event", required = true)
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlSchemaType(name = "NMTOKEN")
            protected String event;

            /**
             * Gets the value of the oid property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOid() {
                return oid;
            }

            /**
             * Sets the value of the oid property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOid(String value) {
                this.oid = value;
            }

            /**
             * Gets the value of the event property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEvent() {
                return event;
            }

            /**
             * Sets the value of the event property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEvent(String value) {
                this.event = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="requirement" type="{http://das.fbk.eu/Composition}ControlFlowType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "requirement"
    })
    public static class ControlFlowRequirements {

        @XmlElement(namespace = "http://das.fbk.eu/Composition", required = true)
        protected List<ControlFlowType> requirement;

        /**
         * Gets the value of the requirement property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the requirement property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRequirement().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ControlFlowType }
         * 
         * 
         */
        public List<ControlFlowType> getRequirement() {
            if (requirement == null) {
                requirement = new ArrayList<ControlFlowType>();
            }
            return this.requirement;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="domainProperty" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="oid" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
     *                 &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "domainProperty"
    })
    public static class DomainProperties {

        @XmlElement(namespace = "http://das.fbk.eu/Composition", required = true)
        protected List<Composition.DomainProperties.DomainProperty> domainProperty;

        /**
         * Gets the value of the domainProperty property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the domainProperty property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDomainProperty().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Composition.DomainProperties.DomainProperty }
         * 
         * 
         */
        public List<Composition.DomainProperties.DomainProperty> getDomainProperty() {
            if (domainProperty == null) {
                domainProperty = new ArrayList<Composition.DomainProperties.DomainProperty>();
            }
            return this.domainProperty;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="oid" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
         *       &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class DomainProperty {

            @XmlAttribute(name = "oid", required = true)
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlSchemaType(name = "NMTOKEN")
            protected String oid;
            @XmlAttribute(name = "type", required = true)
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlSchemaType(name = "NMTOKEN")
            protected String type;

            /**
             * Gets the value of the oid property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOid() {
                return oid;
            }

            /**
             * Sets the value of the oid property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOid(String value) {
                this.oid = value;
            }

            /**
             * Gets the value of the type property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getType() {
                return type;
            }

            /**
             * Sets the value of the type property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setType(String value) {
                this.type = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="fragment" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="assignment" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="o_name" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
     *                           &lt;attribute name="oid" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="sid" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
     *                 &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "fragment"
    })
    public static class Fragments {

        @XmlElement(namespace = "http://das.fbk.eu/Composition", required = true)
        protected List<Composition.Fragments.Fragment> fragment;

        /**
         * Gets the value of the fragment property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the fragment property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFragment().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Composition.Fragments.Fragment }
         * 
         * 
         */
        public List<Composition.Fragments.Fragment> getFragment() {
            if (fragment == null) {
                fragment = new ArrayList<Composition.Fragments.Fragment>();
            }
            return this.fragment;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="assignment" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="o_name" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
         *                 &lt;attribute name="oid" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="sid" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
         *       &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "assignment"
        })
        public static class Fragment {

            @XmlElement(namespace = "http://das.fbk.eu/Composition", required = true)
            protected List<Composition.Fragments.Fragment.Assignment> assignment;
            @XmlAttribute(name = "sid", required = true)
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlSchemaType(name = "NMTOKEN")
            protected String sid;
            @XmlAttribute(name = "type", required = true)
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlSchemaType(name = "NMTOKEN")
            protected String type;

            /**
             * Gets the value of the assignment property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the assignment property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getAssignment().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Composition.Fragments.Fragment.Assignment }
             * 
             * 
             */
            public List<Composition.Fragments.Fragment.Assignment> getAssignment() {
                if (assignment == null) {
                    assignment = new ArrayList<Composition.Fragments.Fragment.Assignment>();
                }
                return this.assignment;
            }

            /**
             * Gets the value of the sid property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSid() {
                return sid;
            }

            /**
             * Sets the value of the sid property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSid(String value) {
                this.sid = value;
            }

            /**
             * Gets the value of the type property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getType() {
                return type;
            }

            /**
             * Sets the value of the type property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setType(String value) {
                this.type = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="o_name" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
             *       &lt;attribute name="oid" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Assignment {

                @XmlAttribute(name = "o_name", required = true)
                @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
                @XmlSchemaType(name = "NMTOKEN")
                protected String oName;
                @XmlAttribute(name = "oid", required = true)
                @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
                @XmlSchemaType(name = "NMTOKEN")
                protected String oid;

                /**
                 * Gets the value of the oName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getOName() {
                    return oName;
                }

                /**
                 * Sets the value of the oName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setOName(String value) {
                    this.oName = value;
                }

                /**
                 * Gets the value of the oid property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getOid() {
                    return oid;
                }

                /**
                 * Sets the value of the oid property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setOid(String value) {
                    this.oid = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="action" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>NMTOKEN">
     *                 &lt;attribute name="sid" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "action"
    })
    public static class NextActions {

        @XmlElement(namespace = "http://das.fbk.eu/Composition", required = true)
        protected List<Composition.NextActions.Action> action;

        /**
         * Gets the value of the action property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the action property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAction().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Composition.NextActions.Action }
         * 
         * 
         */
        public List<Composition.NextActions.Action> getAction() {
            if (action == null) {
                action = new ArrayList<Composition.NextActions.Action>();
            }
            return this.action;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>NMTOKEN">
         *       &lt;attribute name="sid" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Action {

            @XmlValue
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlSchemaType(name = "NMTOKEN")
            protected String value;
            @XmlAttribute(name = "sid", required = true)
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlSchemaType(name = "NMTOKEN")
            protected String sid;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the sid property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSid() {
                return sid;
            }

            /**
             * Sets the value of the sid property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSid(String value) {
                this.sid = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="domainProperties" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="domainProperty" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;simpleContent>
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>NMTOKEN">
     *                           &lt;attribute name="oid" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
     *                         &lt;/extension>
     *                       &lt;/simpleContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="fragments" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="fragment" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;simpleContent>
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>NMTOKEN">
     *                           &lt;attribute name="sid" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
     *                         &lt;/extension>
     *                       &lt;/simpleContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "domainProperties",
        "fragments"
    })
    public static class Runtime {

        @XmlElement(namespace = "http://das.fbk.eu/Composition")
        protected Composition.Runtime.DomainProperties domainProperties;
        @XmlElement(namespace = "http://das.fbk.eu/Composition")
        protected Composition.Runtime.Fragments fragments;

        /**
         * Gets the value of the domainProperties property.
         * 
         * @return
         *     possible object is
         *     {@link Composition.Runtime.DomainProperties }
         *     
         */
        public Composition.Runtime.DomainProperties getDomainProperties() {
            return domainProperties;
        }

        /**
         * Sets the value of the domainProperties property.
         * 
         * @param value
         *     allowed object is
         *     {@link Composition.Runtime.DomainProperties }
         *     
         */
        public void setDomainProperties(Composition.Runtime.DomainProperties value) {
            this.domainProperties = value;
        }

        /**
         * Gets the value of the fragments property.
         * 
         * @return
         *     possible object is
         *     {@link Composition.Runtime.Fragments }
         *     
         */
        public Composition.Runtime.Fragments getFragments() {
            return fragments;
        }

        /**
         * Sets the value of the fragments property.
         * 
         * @param value
         *     allowed object is
         *     {@link Composition.Runtime.Fragments }
         *     
         */
        public void setFragments(Composition.Runtime.Fragments value) {
            this.fragments = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="domainProperty" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;simpleContent>
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>NMTOKEN">
         *                 &lt;attribute name="oid" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
         *               &lt;/extension>
         *             &lt;/simpleContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "domainProperty"
        })
        public static class DomainProperties {

            @XmlElement(namespace = "http://das.fbk.eu/Composition", required = true)
            protected List<Composition.Runtime.DomainProperties.DomainProperty> domainProperty;

            /**
             * Gets the value of the domainProperty property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the domainProperty property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getDomainProperty().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Composition.Runtime.DomainProperties.DomainProperty }
             * 
             * 
             */
            public List<Composition.Runtime.DomainProperties.DomainProperty> getDomainProperty() {
                if (domainProperty == null) {
                    domainProperty = new ArrayList<Composition.Runtime.DomainProperties.DomainProperty>();
                }
                return this.domainProperty;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;simpleContent>
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>NMTOKEN">
             *       &lt;attribute name="oid" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
             *     &lt;/extension>
             *   &lt;/simpleContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class DomainProperty {

                @XmlValue
                @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
                @XmlSchemaType(name = "NMTOKEN")
                protected String value;
                @XmlAttribute(name = "oid")
                @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
                @XmlSchemaType(name = "NMTOKEN")
                protected String oid;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the oid property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getOid() {
                    return oid;
                }

                /**
                 * Sets the value of the oid property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setOid(String value) {
                    this.oid = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="fragment" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;simpleContent>
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>NMTOKEN">
         *                 &lt;attribute name="sid" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
         *               &lt;/extension>
         *             &lt;/simpleContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "fragment"
        })
        public static class Fragments {

            @XmlElement(namespace = "http://das.fbk.eu/Composition", required = true)
            protected List<Composition.Runtime.Fragments.Fragment> fragment;

            /**
             * Gets the value of the fragment property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the fragment property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getFragment().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Composition.Runtime.Fragments.Fragment }
             * 
             * 
             */
            public List<Composition.Runtime.Fragments.Fragment> getFragment() {
                if (fragment == null) {
                    fragment = new ArrayList<Composition.Runtime.Fragments.Fragment>();
                }
                return this.fragment;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;simpleContent>
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>NMTOKEN">
             *       &lt;attribute name="sid" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
             *     &lt;/extension>
             *   &lt;/simpleContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class Fragment {

                @XmlValue
                @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
                @XmlSchemaType(name = "NMTOKEN")
                protected String value;
                @XmlAttribute(name = "sid")
                @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
                @XmlSchemaType(name = "NMTOKEN")
                protected String sid;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the sid property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSid() {
                    return sid;
                }

                /**
                 * Sets the value of the sid property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSid(String value) {
                    this.sid = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="point" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="domainProperty" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" maxOccurs="unbounded"/>
     *                           &lt;/sequence>
     *                           &lt;attribute name="oid" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="priority" type="{http://www.w3.org/2001/XMLSchema}int" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "point"
    })
    public static class Synchronization {

        @XmlElement(namespace = "http://das.fbk.eu/Composition", required = true)
        protected List<Composition.Synchronization.Point> point;

        /**
         * Gets the value of the point property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the point property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPoint().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Composition.Synchronization.Point }
         * 
         * 
         */
        public List<Composition.Synchronization.Point> getPoint() {
            if (point == null) {
                point = new ArrayList<Composition.Synchronization.Point>();
            }
            return this.point;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="domainProperty" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" maxOccurs="unbounded"/>
         *                 &lt;/sequence>
         *                 &lt;attribute name="oid" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="priority" type="{http://www.w3.org/2001/XMLSchema}int" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "domainProperty"
        })
        public static class Point {

            @XmlElement(namespace = "http://das.fbk.eu/Composition", required = true)
            protected List<Composition.Synchronization.Point.DomainProperty> domainProperty;
            @XmlAttribute(name = "priority")
            protected Integer priority;

            /**
             * Gets the value of the domainProperty property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the domainProperty property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getDomainProperty().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Composition.Synchronization.Point.DomainProperty }
             * 
             * 
             */
            public List<Composition.Synchronization.Point.DomainProperty> getDomainProperty() {
                if (domainProperty == null) {
                    domainProperty = new ArrayList<Composition.Synchronization.Point.DomainProperty>();
                }
                return this.domainProperty;
            }

            /**
             * Gets the value of the priority property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getPriority() {
                return priority;
            }

            /**
             * Sets the value of the priority property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setPriority(Integer value) {
                this.priority = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" maxOccurs="unbounded"/>
             *       &lt;/sequence>
             *       &lt;attribute name="oid" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "state"
            })
            public static class DomainProperty {

                @XmlElement(namespace = "http://das.fbk.eu/Composition", required = true)
                @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
                @XmlSchemaType(name = "NMTOKEN")
                protected List<String> state;
                @XmlAttribute(name = "oid", required = true)
                @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
                @XmlSchemaType(name = "NMTOKEN")
                protected String oid;

                /**
                 * Gets the value of the state property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the state property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getState().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link String }
                 * 
                 * 
                 */
                public List<String> getState() {
                    if (state == null) {
                        state = new ArrayList<String>();
                    }
                    return this.state;
                }

                /**
                 * Gets the value of the oid property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getOid() {
                    return oid;
                }

                /**
                 * Sets the value of the oid property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setOid(String value) {
                    this.oid = value;
                }

            }

        }

    }

}
