//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.23 at 01:16:59 PM CET 
//


package eu.fbk.das.process.engine.api.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				An hard-coded activity to be performed to handle
 * 				special
 * 				cases
 * 			
 * 
 * <p>Java class for concreteType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="concreteType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://das.fbk.eu/Process}activityType">
 *       &lt;attribute name="returnsTo" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "concreteType")
public class ConcreteType
    extends ActivityType
{

    @XmlAttribute(name = "returnsTo")
    protected String returnsTo;

    /**
     * Gets the value of the returnsTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReturnsTo() {
        return returnsTo;
    }

    /**
     * Sets the value of the returnsTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReturnsTo(String value) {
        this.returnsTo = value;
    }

}
