//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.23 at 01:16:59 PM CET 
//


package eu.fbk.das.process.engine.api.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for ControlFlowType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ControlFlowType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="premise" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;group ref="{http://das.fbk.eu/Composition}clause" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="result" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;group ref="{http://das.fbk.eu/Composition}clause" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="priority" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ControlFlowType", namespace = "http://das.fbk.eu/Composition", propOrder = {
    "premise",
    "result"
})
public class ControlFlowType {

    protected ControlFlowType.Premise premise;
    @XmlElement(required = true)
    protected List<ControlFlowType.Result> result;

    /**
     * Gets the value of the premise property.
     * 
     * @return
     *     possible object is
     *     {@link ControlFlowType.Premise }
     *     
     */
    public ControlFlowType.Premise getPremise() {
        return premise;
    }

    /**
     * Sets the value of the premise property.
     * 
     * @param value
     *     allowed object is
     *     {@link ControlFlowType.Premise }
     *     
     */
    public void setPremise(ControlFlowType.Premise value) {
        this.premise = value;
    }

    /**
     * Gets the value of the result property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the result property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getResult().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ControlFlowType.Result }
     * 
     * 
     */
    public List<ControlFlowType.Result> getResult() {
        if (result == null) {
            result = new ArrayList<ControlFlowType.Result>();
        }
        return this.result;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;group ref="{http://das.fbk.eu/Composition}clause" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "clause"
    })
    public static class Premise {

        @XmlElements({
            @XmlElement(name = "true", namespace = "http://das.fbk.eu/Composition"),
            @XmlElement(name = "and", namespace = "http://das.fbk.eu/Composition", type = ControlFlowType.Result.And.class),
            @XmlElement(name = "then", namespace = "http://das.fbk.eu/Composition", type = ControlFlowType.Result.Then.class),
            @XmlElement(name = "or", namespace = "http://das.fbk.eu/Composition", type = ControlFlowType.Result.Or.class),
            @XmlElement(name = "trycatch", namespace = "http://das.fbk.eu/Composition", type = ControlFlowType.Result.Trycatch.class),
            @XmlElement(name = "action", namespace = "http://das.fbk.eu/Composition", type = ControlFlowType.Result.Action.class),
            @XmlElement(name = "event", namespace = "http://das.fbk.eu/Composition", type = ControlFlowType.Result.Event.class),
            @XmlElement(name = "situation", namespace = "http://das.fbk.eu/Composition", type = ControlFlowType.Result.Situation.class)
        })
        protected List<Object> clause;

        /**
         * Gets the value of the clause property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the clause property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getClause().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Object }
         * {@link ControlFlowType.Result.And }
         * {@link ControlFlowType.Result.Then }
         * {@link ControlFlowType.Result.Or }
         * {@link ControlFlowType.Result.Trycatch }
         * {@link ControlFlowType.Result.Action }
         * {@link ControlFlowType.Result.Event }
         * {@link ControlFlowType.Result.Situation }
         * 
         * 
         */
        public List<Object> getClause() {
            if (clause == null) {
                clause = new ArrayList<Object>();
            }
            return this.clause;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;group ref="{http://das.fbk.eu/Composition}clause" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *       &lt;attribute name="priority" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "clause"
    })
    public static class Result {

        @XmlElements({
            @XmlElement(name = "true", namespace = "http://das.fbk.eu/Composition"),
            @XmlElement(name = "and", namespace = "http://das.fbk.eu/Composition", type = ControlFlowType.Result.And.class),
            @XmlElement(name = "then", namespace = "http://das.fbk.eu/Composition", type = ControlFlowType.Result.Then.class),
            @XmlElement(name = "or", namespace = "http://das.fbk.eu/Composition", type = ControlFlowType.Result.Or.class),
            @XmlElement(name = "trycatch", namespace = "http://das.fbk.eu/Composition", type = ControlFlowType.Result.Trycatch.class),
            @XmlElement(name = "action", namespace = "http://das.fbk.eu/Composition", type = ControlFlowType.Result.Action.class),
            @XmlElement(name = "event", namespace = "http://das.fbk.eu/Composition", type = ControlFlowType.Result.Event.class),
            @XmlElement(name = "situation", namespace = "http://das.fbk.eu/Composition", type = ControlFlowType.Result.Situation.class)
        })
        protected List<Object> clause;
        @XmlAttribute(name = "priority", required = true)
        protected int priority;

        /**
         * Gets the value of the clause property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the clause property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getClause().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Object }
         * {@link ControlFlowType.Result.And }
         * {@link ControlFlowType.Result.Then }
         * {@link ControlFlowType.Result.Or }
         * {@link ControlFlowType.Result.Trycatch }
         * {@link ControlFlowType.Result.Action }
         * {@link ControlFlowType.Result.Event }
         * {@link ControlFlowType.Result.Situation }
         * 
         * 
         */
        public List<Object> getClause() {
            if (clause == null) {
                clause = new ArrayList<Object>();
            }
            return this.clause;
        }

        /**
         * Gets the value of the priority property.
         * 
         */
        public int getPriority() {
            return priority;
        }

        /**
         * Sets the value of the priority property.
         * 
         */
        public void setPriority(int value) {
            this.priority = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="condition" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="domainProperty" maxOccurs="unbounded" minOccurs="0">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" maxOccurs="unbounded"/>
         *                           &lt;/sequence>
         *                           &lt;attribute name="oid" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="sid" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
         *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "condition"
        })
        public static class Action {

            @XmlElement(namespace = "http://das.fbk.eu/Composition")
            protected ControlFlowType.Result.Action.Condition condition;
            @XmlAttribute(name = "sid", required = true)
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlSchemaType(name = "NMTOKEN")
            protected String sid;
            @XmlAttribute(name = "name", required = true)
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlSchemaType(name = "NMTOKEN")
            protected String name;

            /**
             * Gets the value of the condition property.
             * 
             * @return
             *     possible object is
             *     {@link ControlFlowType.Result.Action.Condition }
             *     
             */
            public ControlFlowType.Result.Action.Condition getCondition() {
                return condition;
            }

            /**
             * Sets the value of the condition property.
             * 
             * @param value
             *     allowed object is
             *     {@link ControlFlowType.Result.Action.Condition }
             *     
             */
            public void setCondition(ControlFlowType.Result.Action.Condition value) {
                this.condition = value;
            }

            /**
             * Gets the value of the sid property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSid() {
                return sid;
            }

            /**
             * Sets the value of the sid property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSid(String value) {
                this.sid = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="domainProperty" maxOccurs="unbounded" minOccurs="0">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" maxOccurs="unbounded"/>
             *                 &lt;/sequence>
             *                 &lt;attribute name="oid" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "domainProperty"
            })
            public static class Condition {

                @XmlElement(namespace = "http://das.fbk.eu/Composition")
                protected List<ControlFlowType.Result.Action.Condition.DomainProperty> domainProperty;

                /**
                 * Gets the value of the domainProperty property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the domainProperty property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getDomainProperty().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link ControlFlowType.Result.Action.Condition.DomainProperty }
                 * 
                 * 
                 */
                public List<ControlFlowType.Result.Action.Condition.DomainProperty> getDomainProperty() {
                    if (domainProperty == null) {
                        domainProperty = new ArrayList<ControlFlowType.Result.Action.Condition.DomainProperty>();
                    }
                    return this.domainProperty;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" maxOccurs="unbounded"/>
                 *       &lt;/sequence>
                 *       &lt;attribute name="oid" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "state"
                })
                public static class DomainProperty {

                    @XmlElement(namespace = "http://das.fbk.eu/Composition", required = true)
                    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
                    @XmlSchemaType(name = "NMTOKEN")
                    protected List<String> state;
                    @XmlAttribute(name = "oid", required = true)
                    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
                    @XmlSchemaType(name = "NMTOKEN")
                    protected String oid;

                    /**
                     * Gets the value of the state property.
                     * 
                     * <p>
                     * This accessor method returns a reference to the live list,
                     * not a snapshot. Therefore any modification you make to the
                     * returned list will be present inside the JAXB object.
                     * This is why there is not a <CODE>set</CODE> method for the state property.
                     * 
                     * <p>
                     * For example, to add a new item, do as follows:
                     * <pre>
                     *    getState().add(newItem);
                     * </pre>
                     * 
                     * 
                     * <p>
                     * Objects of the following type(s) are allowed in the list
                     * {@link String }
                     * 
                     * 
                     */
                    public List<String> getState() {
                        if (state == null) {
                            state = new ArrayList<String>();
                        }
                        return this.state;
                    }

                    /**
                     * Gets the value of the oid property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getOid() {
                        return oid;
                    }

                    /**
                     * Sets the value of the oid property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setOid(String value) {
                        this.oid = value;
                    }

                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;group ref="{http://das.fbk.eu/Composition}clause" maxOccurs="unbounded" minOccurs="2"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "clause"
        })
        public static class And {

            @XmlElements({
                @XmlElement(name = "true", namespace = "http://das.fbk.eu/Composition"),
                @XmlElement(name = "and", namespace = "http://das.fbk.eu/Composition", type = ControlFlowType.Result.And.class),
                @XmlElement(name = "then", namespace = "http://das.fbk.eu/Composition", type = ControlFlowType.Result.Then.class),
                @XmlElement(name = "or", namespace = "http://das.fbk.eu/Composition", type = ControlFlowType.Result.Or.class),
                @XmlElement(name = "trycatch", namespace = "http://das.fbk.eu/Composition", type = ControlFlowType.Result.Trycatch.class),
                @XmlElement(name = "action", namespace = "http://das.fbk.eu/Composition", type = ControlFlowType.Result.Action.class),
                @XmlElement(name = "event", namespace = "http://das.fbk.eu/Composition", type = ControlFlowType.Result.Event.class),
                @XmlElement(name = "situation", namespace = "http://das.fbk.eu/Composition", type = ControlFlowType.Result.Situation.class)
            })
            protected List<Object> clause;

            /**
             * Gets the value of the clause property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the clause property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getClause().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Object }
             * {@link ControlFlowType.Result.And }
             * {@link ControlFlowType.Result.Then }
             * {@link ControlFlowType.Result.Or }
             * {@link ControlFlowType.Result.Trycatch }
             * {@link ControlFlowType.Result.Action }
             * {@link ControlFlowType.Result.Event }
             * {@link ControlFlowType.Result.Situation }
             * 
             * 
             */
            public List<Object> getClause() {
                if (clause == null) {
                    clause = new ArrayList<Object>();
                }
                return this.clause;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="condition" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="domainProperty" maxOccurs="unbounded" minOccurs="0">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" maxOccurs="unbounded"/>
         *                           &lt;/sequence>
         *                           &lt;attribute name="oid" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="oid" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
         *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "condition"
        })
        public static class Event {

            @XmlElement(namespace = "http://das.fbk.eu/Composition")
            protected ControlFlowType.Result.Event.Condition condition;
            @XmlAttribute(name = "oid", required = true)
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlSchemaType(name = "NMTOKEN")
            protected String oid;
            @XmlAttribute(name = "name", required = true)
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlSchemaType(name = "NMTOKEN")
            protected String name;

            /**
             * Gets the value of the condition property.
             * 
             * @return
             *     possible object is
             *     {@link ControlFlowType.Result.Event.Condition }
             *     
             */
            public ControlFlowType.Result.Event.Condition getCondition() {
                return condition;
            }

            /**
             * Sets the value of the condition property.
             * 
             * @param value
             *     allowed object is
             *     {@link ControlFlowType.Result.Event.Condition }
             *     
             */
            public void setCondition(ControlFlowType.Result.Event.Condition value) {
                this.condition = value;
            }

            /**
             * Gets the value of the oid property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOid() {
                return oid;
            }

            /**
             * Sets the value of the oid property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOid(String value) {
                this.oid = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="domainProperty" maxOccurs="unbounded" minOccurs="0">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" maxOccurs="unbounded"/>
             *                 &lt;/sequence>
             *                 &lt;attribute name="oid" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "domainProperty"
            })
            public static class Condition {

                @XmlElement(namespace = "http://das.fbk.eu/Composition")
                protected List<ControlFlowType.Result.Event.Condition.DomainProperty> domainProperty;

                /**
                 * Gets the value of the domainProperty property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the domainProperty property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getDomainProperty().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link ControlFlowType.Result.Event.Condition.DomainProperty }
                 * 
                 * 
                 */
                public List<ControlFlowType.Result.Event.Condition.DomainProperty> getDomainProperty() {
                    if (domainProperty == null) {
                        domainProperty = new ArrayList<ControlFlowType.Result.Event.Condition.DomainProperty>();
                    }
                    return this.domainProperty;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" maxOccurs="unbounded"/>
                 *       &lt;/sequence>
                 *       &lt;attribute name="oid" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "state"
                })
                public static class DomainProperty {

                    @XmlElement(namespace = "http://das.fbk.eu/Composition", required = true)
                    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
                    @XmlSchemaType(name = "NMTOKEN")
                    protected List<String> state;
                    @XmlAttribute(name = "oid", required = true)
                    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
                    @XmlSchemaType(name = "NMTOKEN")
                    protected String oid;

                    /**
                     * Gets the value of the state property.
                     * 
                     * <p>
                     * This accessor method returns a reference to the live list,
                     * not a snapshot. Therefore any modification you make to the
                     * returned list will be present inside the JAXB object.
                     * This is why there is not a <CODE>set</CODE> method for the state property.
                     * 
                     * <p>
                     * For example, to add a new item, do as follows:
                     * <pre>
                     *    getState().add(newItem);
                     * </pre>
                     * 
                     * 
                     * <p>
                     * Objects of the following type(s) are allowed in the list
                     * {@link String }
                     * 
                     * 
                     */
                    public List<String> getState() {
                        if (state == null) {
                            state = new ArrayList<String>();
                        }
                        return this.state;
                    }

                    /**
                     * Gets the value of the oid property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getOid() {
                        return oid;
                    }

                    /**
                     * Sets the value of the oid property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setOid(String value) {
                        this.oid = value;
                    }

                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;group ref="{http://das.fbk.eu/Composition}clause" maxOccurs="unbounded" minOccurs="2"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "clause"
        })
        public static class Or {

            @XmlElements({
                @XmlElement(name = "true", namespace = "http://das.fbk.eu/Composition"),
                @XmlElement(name = "and", namespace = "http://das.fbk.eu/Composition", type = ControlFlowType.Result.And.class),
                @XmlElement(name = "then", namespace = "http://das.fbk.eu/Composition", type = ControlFlowType.Result.Then.class),
                @XmlElement(name = "or", namespace = "http://das.fbk.eu/Composition", type = ControlFlowType.Result.Or.class),
                @XmlElement(name = "trycatch", namespace = "http://das.fbk.eu/Composition", type = ControlFlowType.Result.Trycatch.class),
                @XmlElement(name = "action", namespace = "http://das.fbk.eu/Composition", type = ControlFlowType.Result.Action.class),
                @XmlElement(name = "event", namespace = "http://das.fbk.eu/Composition", type = ControlFlowType.Result.Event.class),
                @XmlElement(name = "situation", namespace = "http://das.fbk.eu/Composition", type = ControlFlowType.Result.Situation.class)
            })
            protected List<Object> clause;

            /**
             * Gets the value of the clause property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the clause property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getClause().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Object }
             * {@link ControlFlowType.Result.And }
             * {@link ControlFlowType.Result.Then }
             * {@link ControlFlowType.Result.Or }
             * {@link ControlFlowType.Result.Trycatch }
             * {@link ControlFlowType.Result.Action }
             * {@link ControlFlowType.Result.Event }
             * {@link ControlFlowType.Result.Situation }
             * 
             * 
             */
            public List<Object> getClause() {
                if (clause == null) {
                    clause = new ArrayList<Object>();
                }
                return this.clause;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="domainProperty" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" maxOccurs="unbounded"/>
         *                 &lt;/sequence>
         *                 &lt;attribute name="oid" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "domainProperty"
        })
        public static class Situation {

            @XmlElement(namespace = "http://das.fbk.eu/Composition")
            protected List<ControlFlowType.Result.Situation.DomainProperty> domainProperty;

            /**
             * Gets the value of the domainProperty property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the domainProperty property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getDomainProperty().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link ControlFlowType.Result.Situation.DomainProperty }
             * 
             * 
             */
            public List<ControlFlowType.Result.Situation.DomainProperty> getDomainProperty() {
                if (domainProperty == null) {
                    domainProperty = new ArrayList<ControlFlowType.Result.Situation.DomainProperty>();
                }
                return this.domainProperty;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" maxOccurs="unbounded"/>
             *       &lt;/sequence>
             *       &lt;attribute name="oid" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "state"
            })
            public static class DomainProperty {

                @XmlElement(namespace = "http://das.fbk.eu/Composition", required = true)
                @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
                @XmlSchemaType(name = "NMTOKEN")
                protected List<String> state;
                @XmlAttribute(name = "oid", required = true)
                @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
                @XmlSchemaType(name = "NMTOKEN")
                protected String oid;

                /**
                 * Gets the value of the state property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the state property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getState().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link String }
                 * 
                 * 
                 */
                public List<String> getState() {
                    if (state == null) {
                        state = new ArrayList<String>();
                    }
                    return this.state;
                }

                /**
                 * Gets the value of the oid property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getOid() {
                    return oid;
                }

                /**
                 * Sets the value of the oid property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setOid(String value) {
                    this.oid = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;group ref="{http://das.fbk.eu/Composition}clause" maxOccurs="unbounded" minOccurs="2"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "clause"
        })
        public static class Then {

            @XmlElements({
                @XmlElement(name = "true", namespace = "http://das.fbk.eu/Composition"),
                @XmlElement(name = "and", namespace = "http://das.fbk.eu/Composition", type = ControlFlowType.Result.And.class),
                @XmlElement(name = "then", namespace = "http://das.fbk.eu/Composition", type = ControlFlowType.Result.Then.class),
                @XmlElement(name = "or", namespace = "http://das.fbk.eu/Composition", type = ControlFlowType.Result.Or.class),
                @XmlElement(name = "trycatch", namespace = "http://das.fbk.eu/Composition", type = ControlFlowType.Result.Trycatch.class),
                @XmlElement(name = "action", namespace = "http://das.fbk.eu/Composition", type = ControlFlowType.Result.Action.class),
                @XmlElement(name = "event", namespace = "http://das.fbk.eu/Composition", type = ControlFlowType.Result.Event.class),
                @XmlElement(name = "situation", namespace = "http://das.fbk.eu/Composition", type = ControlFlowType.Result.Situation.class)
            })
            protected List<Object> clause;

            /**
             * Gets the value of the clause property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the clause property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getClause().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Object }
             * {@link ControlFlowType.Result.And }
             * {@link ControlFlowType.Result.Then }
             * {@link ControlFlowType.Result.Or }
             * {@link ControlFlowType.Result.Trycatch }
             * {@link ControlFlowType.Result.Action }
             * {@link ControlFlowType.Result.Event }
             * {@link ControlFlowType.Result.Situation }
             * 
             * 
             */
            public List<Object> getClause() {
                if (clause == null) {
                    clause = new ArrayList<Object>();
                }
                return this.clause;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="try">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;group ref="{http://das.fbk.eu/Composition}clause" maxOccurs="unbounded"/>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="catch" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="condition">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;group ref="{http://das.fbk.eu/Composition}clause" maxOccurs="unbounded"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                   &lt;element name="reaction">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;group ref="{http://das.fbk.eu/Composition}clause" maxOccurs="unbounded"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "_try",
            "_catch"
        })
        public static class Trycatch {

            @XmlElement(name = "try", namespace = "http://das.fbk.eu/Composition", required = true)
            protected ControlFlowType.Result.Trycatch.Try _try;
            @XmlElement(name = "catch", namespace = "http://das.fbk.eu/Composition")
            protected List<ControlFlowType.Result.Trycatch.Catch> _catch;

            /**
             * Gets the value of the try property.
             * 
             * @return
             *     possible object is
             *     {@link ControlFlowType.Result.Trycatch.Try }
             *     
             */
            public ControlFlowType.Result.Trycatch.Try getTry() {
                return _try;
            }

            /**
             * Sets the value of the try property.
             * 
             * @param value
             *     allowed object is
             *     {@link ControlFlowType.Result.Trycatch.Try }
             *     
             */
            public void setTry(ControlFlowType.Result.Trycatch.Try value) {
                this._try = value;
            }

            /**
             * Gets the value of the catch property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the catch property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getCatch().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link ControlFlowType.Result.Trycatch.Catch }
             * 
             * 
             */
            public List<ControlFlowType.Result.Trycatch.Catch> getCatch() {
                if (_catch == null) {
                    _catch = new ArrayList<ControlFlowType.Result.Trycatch.Catch>();
                }
                return this._catch;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="condition">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;group ref="{http://das.fbk.eu/Composition}clause" maxOccurs="unbounded"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *         &lt;element name="reaction">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;group ref="{http://das.fbk.eu/Composition}clause" maxOccurs="unbounded"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "condition",
                "reaction"
            })
            public static class Catch {

                @XmlElement(namespace = "http://das.fbk.eu/Composition", required = true)
                protected ControlFlowType.Result.Trycatch.Catch.Condition condition;
                @XmlElement(namespace = "http://das.fbk.eu/Composition", required = true)
                protected ControlFlowType.Result.Trycatch.Catch.Reaction reaction;

                /**
                 * Gets the value of the condition property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link ControlFlowType.Result.Trycatch.Catch.Condition }
                 *     
                 */
                public ControlFlowType.Result.Trycatch.Catch.Condition getCondition() {
                    return condition;
                }

                /**
                 * Sets the value of the condition property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link ControlFlowType.Result.Trycatch.Catch.Condition }
                 *     
                 */
                public void setCondition(ControlFlowType.Result.Trycatch.Catch.Condition value) {
                    this.condition = value;
                }

                /**
                 * Gets the value of the reaction property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link ControlFlowType.Result.Trycatch.Catch.Reaction }
                 *     
                 */
                public ControlFlowType.Result.Trycatch.Catch.Reaction getReaction() {
                    return reaction;
                }

                /**
                 * Sets the value of the reaction property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link ControlFlowType.Result.Trycatch.Catch.Reaction }
                 *     
                 */
                public void setReaction(ControlFlowType.Result.Trycatch.Catch.Reaction value) {
                    this.reaction = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;group ref="{http://das.fbk.eu/Composition}clause" maxOccurs="unbounded"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "clause"
                })
                public static class Condition {

                    @XmlElements({
                        @XmlElement(name = "true", namespace = "http://das.fbk.eu/Composition"),
                        @XmlElement(name = "and", namespace = "http://das.fbk.eu/Composition", type = ControlFlowType.Result.And.class),
                        @XmlElement(name = "then", namespace = "http://das.fbk.eu/Composition", type = ControlFlowType.Result.Then.class),
                        @XmlElement(name = "or", namespace = "http://das.fbk.eu/Composition", type = ControlFlowType.Result.Or.class),
                        @XmlElement(name = "trycatch", namespace = "http://das.fbk.eu/Composition", type = ControlFlowType.Result.Trycatch.class),
                        @XmlElement(name = "action", namespace = "http://das.fbk.eu/Composition", type = ControlFlowType.Result.Action.class),
                        @XmlElement(name = "event", namespace = "http://das.fbk.eu/Composition", type = ControlFlowType.Result.Event.class),
                        @XmlElement(name = "situation", namespace = "http://das.fbk.eu/Composition", type = ControlFlowType.Result.Situation.class)
                    })
                    protected List<Object> clause;

                    /**
                     * Gets the value of the clause property.
                     * 
                     * <p>
                     * This accessor method returns a reference to the live list,
                     * not a snapshot. Therefore any modification you make to the
                     * returned list will be present inside the JAXB object.
                     * This is why there is not a <CODE>set</CODE> method for the clause property.
                     * 
                     * <p>
                     * For example, to add a new item, do as follows:
                     * <pre>
                     *    getClause().add(newItem);
                     * </pre>
                     * 
                     * 
                     * <p>
                     * Objects of the following type(s) are allowed in the list
                     * {@link Object }
                     * {@link ControlFlowType.Result.And }
                     * {@link ControlFlowType.Result.Then }
                     * {@link ControlFlowType.Result.Or }
                     * {@link ControlFlowType.Result.Trycatch }
                     * {@link ControlFlowType.Result.Action }
                     * {@link ControlFlowType.Result.Event }
                     * {@link ControlFlowType.Result.Situation }
                     * 
                     * 
                     */
                    public List<Object> getClause() {
                        if (clause == null) {
                            clause = new ArrayList<Object>();
                        }
                        return this.clause;
                    }

                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;group ref="{http://das.fbk.eu/Composition}clause" maxOccurs="unbounded"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "clause"
                })
                public static class Reaction {

                    @XmlElements({
                        @XmlElement(name = "true", namespace = "http://das.fbk.eu/Composition"),
                        @XmlElement(name = "and", namespace = "http://das.fbk.eu/Composition", type = ControlFlowType.Result.And.class),
                        @XmlElement(name = "then", namespace = "http://das.fbk.eu/Composition", type = ControlFlowType.Result.Then.class),
                        @XmlElement(name = "or", namespace = "http://das.fbk.eu/Composition", type = ControlFlowType.Result.Or.class),
                        @XmlElement(name = "trycatch", namespace = "http://das.fbk.eu/Composition", type = ControlFlowType.Result.Trycatch.class),
                        @XmlElement(name = "action", namespace = "http://das.fbk.eu/Composition", type = ControlFlowType.Result.Action.class),
                        @XmlElement(name = "event", namespace = "http://das.fbk.eu/Composition", type = ControlFlowType.Result.Event.class),
                        @XmlElement(name = "situation", namespace = "http://das.fbk.eu/Composition", type = ControlFlowType.Result.Situation.class)
                    })
                    protected List<Object> clause;

                    /**
                     * Gets the value of the clause property.
                     * 
                     * <p>
                     * This accessor method returns a reference to the live list,
                     * not a snapshot. Therefore any modification you make to the
                     * returned list will be present inside the JAXB object.
                     * This is why there is not a <CODE>set</CODE> method for the clause property.
                     * 
                     * <p>
                     * For example, to add a new item, do as follows:
                     * <pre>
                     *    getClause().add(newItem);
                     * </pre>
                     * 
                     * 
                     * <p>
                     * Objects of the following type(s) are allowed in the list
                     * {@link Object }
                     * {@link ControlFlowType.Result.And }
                     * {@link ControlFlowType.Result.Then }
                     * {@link ControlFlowType.Result.Or }
                     * {@link ControlFlowType.Result.Trycatch }
                     * {@link ControlFlowType.Result.Action }
                     * {@link ControlFlowType.Result.Event }
                     * {@link ControlFlowType.Result.Situation }
                     * 
                     * 
                     */
                    public List<Object> getClause() {
                        if (clause == null) {
                            clause = new ArrayList<Object>();
                        }
                        return this.clause;
                    }

                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;group ref="{http://das.fbk.eu/Composition}clause" maxOccurs="unbounded"/>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "clause"
            })
            public static class Try {

                @XmlElements({
                    @XmlElement(name = "true", namespace = "http://das.fbk.eu/Composition"),
                    @XmlElement(name = "and", namespace = "http://das.fbk.eu/Composition", type = ControlFlowType.Result.And.class),
                    @XmlElement(name = "then", namespace = "http://das.fbk.eu/Composition", type = ControlFlowType.Result.Then.class),
                    @XmlElement(name = "or", namespace = "http://das.fbk.eu/Composition", type = ControlFlowType.Result.Or.class),
                    @XmlElement(name = "trycatch", namespace = "http://das.fbk.eu/Composition", type = ControlFlowType.Result.Trycatch.class),
                    @XmlElement(name = "action", namespace = "http://das.fbk.eu/Composition", type = ControlFlowType.Result.Action.class),
                    @XmlElement(name = "event", namespace = "http://das.fbk.eu/Composition", type = ControlFlowType.Result.Event.class),
                    @XmlElement(name = "situation", namespace = "http://das.fbk.eu/Composition", type = ControlFlowType.Result.Situation.class)
                })
                protected List<Object> clause;

                /**
                 * Gets the value of the clause property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the clause property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getClause().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link Object }
                 * {@link ControlFlowType.Result.And }
                 * {@link ControlFlowType.Result.Then }
                 * {@link ControlFlowType.Result.Or }
                 * {@link ControlFlowType.Result.Trycatch }
                 * {@link ControlFlowType.Result.Action }
                 * {@link ControlFlowType.Result.Event }
                 * {@link ControlFlowType.Result.Situation }
                 * 
                 * 
                 */
                public List<Object> getClause() {
                    if (clause == null) {
                        clause = new ArrayList<Object>();
                    }
                    return this.clause;
                }

            }

        }

    }

}
