//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.23 at 01:16:59 PM CET 
//


package eu.fbk.das.process.engine.api.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="state" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://das.fbk.eu/Process>DomainPropertyStateType">
 *                 &lt;attribute name="isInitial" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="event" type="{http://das.fbk.eu/Process}DomainPropertyEventType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="transition" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="from" type="{http://das.fbk.eu/Process}DomainPropertyStateType"/>
 *                   &lt;element name="to" type="{http://das.fbk.eu/Process}DomainPropertyStateType"/>
 *                   &lt;element name="event" type="{http://das.fbk.eu/Process}DomainPropertyEventType"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="isControllable" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "state",
    "event",
    "transition"
})
@XmlRootElement(name = "domainProperty")
public class DomainProperty {

    @XmlElement(required = true)
    protected List<DomainProperty.State> state;
    protected List<DomainPropertyEventType> event;
    protected List<DomainProperty.Transition> transition;
    @XmlAttribute(name = "id", required = true)
    protected String id;

    /**
     * Gets the value of the state property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the state property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getState().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DomainProperty.State }
     * 
     * 
     */
    public List<DomainProperty.State> getState() {
        if (state == null) {
            state = new ArrayList<DomainProperty.State>();
        }
        return this.state;
    }

    /**
     * Gets the value of the event property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the event property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEvent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DomainPropertyEventType }
     * 
     * 
     */
    public List<DomainPropertyEventType> getEvent() {
        if (event == null) {
            event = new ArrayList<DomainPropertyEventType>();
        }
        return this.event;
    }

    /**
     * Gets the value of the transition property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the transition property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTransition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DomainProperty.Transition }
     * 
     * 
     */
    public List<DomainProperty.Transition> getTransition() {
        if (transition == null) {
            transition = new ArrayList<DomainProperty.Transition>();
        }
        return this.transition;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://das.fbk.eu/Process>DomainPropertyStateType">
     *       &lt;attribute name="isInitial" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class State
        extends DomainPropertyStateType
    {

        @XmlAttribute(name = "isInitial")
        protected Boolean isInitial;

        /**
         * Gets the value of the isInitial property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isIsInitial() {
            return isInitial;
        }

        /**
         * Sets the value of the isInitial property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setIsInitial(Boolean value) {
            this.isInitial = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="from" type="{http://das.fbk.eu/Process}DomainPropertyStateType"/>
     *         &lt;element name="to" type="{http://das.fbk.eu/Process}DomainPropertyStateType"/>
     *         &lt;element name="event" type="{http://das.fbk.eu/Process}DomainPropertyEventType"/>
     *       &lt;/sequence>
     *       &lt;attribute name="isControllable" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "from",
        "to",
        "event"
    })
    public static class Transition {

        @XmlElement(required = true)
        protected DomainPropertyStateType from;
        @XmlElement(required = true)
        protected DomainPropertyStateType to;
        @XmlElement(required = true)
        protected DomainPropertyEventType event;
        @XmlAttribute(name = "isControllable", required = true)
        protected boolean isControllable;

        /**
         * Gets the value of the from property.
         * 
         * @return
         *     possible object is
         *     {@link DomainPropertyStateType }
         *     
         */
        public DomainPropertyStateType getFrom() {
            return from;
        }

        /**
         * Sets the value of the from property.
         * 
         * @param value
         *     allowed object is
         *     {@link DomainPropertyStateType }
         *     
         */
        public void setFrom(DomainPropertyStateType value) {
            this.from = value;
        }

        /**
         * Gets the value of the to property.
         * 
         * @return
         *     possible object is
         *     {@link DomainPropertyStateType }
         *     
         */
        public DomainPropertyStateType getTo() {
            return to;
        }

        /**
         * Sets the value of the to property.
         * 
         * @param value
         *     allowed object is
         *     {@link DomainPropertyStateType }
         *     
         */
        public void setTo(DomainPropertyStateType value) {
            this.to = value;
        }

        /**
         * Gets the value of the event property.
         * 
         * @return
         *     possible object is
         *     {@link DomainPropertyEventType }
         *     
         */
        public DomainPropertyEventType getEvent() {
            return event;
        }

        /**
         * Sets the value of the event property.
         * 
         * @param value
         *     allowed object is
         *     {@link DomainPropertyEventType }
         *     
         */
        public void setEvent(DomainPropertyEventType value) {
            this.event = value;
        }

        /**
         * Gets the value of the isControllable property.
         * 
         */
        public boolean isIsControllable() {
            return isControllable;
        }

        /**
         * Sets the value of the isControllable property.
         * 
         */
        public void setIsControllable(boolean value) {
            this.isControllable = value;
        }

    }

}
