//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.23 at 01:16:59 PM CET 
//


package eu.fbk.das.process.engine.api.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eu.fbk.das.process.engine.api.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Annotations_QNAME = new QName("http://das.fbk.eu/Annotation", "annotations");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.fbk.das.process.engine.api.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DomainObject }
     * 
     */
    public DomainObject createDomainObject() {
        return new DomainObject();
    }

    /**
     * Create an instance of {@link eu.fbk.das.process.engine.api.jaxb.DomainProperty }
     * 
     */
    public eu.fbk.das.process.engine.api.jaxb.DomainProperty createDomainProperty() {
        return new eu.fbk.das.process.engine.api.jaxb.DomainProperty();
    }

    /**
     * Create an instance of {@link eu.fbk.das.process.engine.api.jaxb.Fragment }
     * 
     */
    public eu.fbk.das.process.engine.api.jaxb.Fragment createFragment() {
        return new eu.fbk.das.process.engine.api.jaxb.Fragment();
    }

    /**
     * Create an instance of {@link Composition }
     * 
     */
    public Composition createComposition() {
        return new Composition();
    }

    /**
     * Create an instance of {@link ControlFlowType }
     * 
     */
    public ControlFlowType createControlFlowType() {
        return new ControlFlowType();
    }

    /**
     * Create an instance of {@link ControlFlowType.Result }
     * 
     */
    public ControlFlowType.Result createControlFlowTypeResult() {
        return new ControlFlowType.Result();
    }

    /**
     * Create an instance of {@link ControlFlowType.Result.Situation }
     * 
     */
    public ControlFlowType.Result.Situation createControlFlowTypeResultSituation() {
        return new ControlFlowType.Result.Situation();
    }

    /**
     * Create an instance of {@link ControlFlowType.Result.Event }
     * 
     */
    public ControlFlowType.Result.Event createControlFlowTypeResultEvent() {
        return new ControlFlowType.Result.Event();
    }

    /**
     * Create an instance of {@link ControlFlowType.Result.Event.Condition }
     * 
     */
    public ControlFlowType.Result.Event.Condition createControlFlowTypeResultEventCondition() {
        return new ControlFlowType.Result.Event.Condition();
    }

    /**
     * Create an instance of {@link ControlFlowType.Result.Action }
     * 
     */
    public ControlFlowType.Result.Action createControlFlowTypeResultAction() {
        return new ControlFlowType.Result.Action();
    }

    /**
     * Create an instance of {@link ControlFlowType.Result.Action.Condition }
     * 
     */
    public ControlFlowType.Result.Action.Condition createControlFlowTypeResultActionCondition() {
        return new ControlFlowType.Result.Action.Condition();
    }

    /**
     * Create an instance of {@link ControlFlowType.Result.Trycatch }
     * 
     */
    public ControlFlowType.Result.Trycatch createControlFlowTypeResultTrycatch() {
        return new ControlFlowType.Result.Trycatch();
    }

    /**
     * Create an instance of {@link ControlFlowType.Result.Trycatch.Catch }
     * 
     */
    public ControlFlowType.Result.Trycatch.Catch createControlFlowTypeResultTrycatchCatch() {
        return new ControlFlowType.Result.Trycatch.Catch();
    }

    /**
     * Create an instance of {@link Composition.Runtime }
     * 
     */
    public Composition.Runtime createCompositionRuntime() {
        return new Composition.Runtime();
    }

    /**
     * Create an instance of {@link Composition.Runtime.Fragments }
     * 
     */
    public Composition.Runtime.Fragments createCompositionRuntimeFragments() {
        return new Composition.Runtime.Fragments();
    }

    /**
     * Create an instance of {@link Composition.Runtime.DomainProperties }
     * 
     */
    public Composition.Runtime.DomainProperties createCompositionRuntimeDomainProperties() {
        return new Composition.Runtime.DomainProperties();
    }

    /**
     * Create an instance of {@link Composition.NextActions }
     * 
     */
    public Composition.NextActions createCompositionNextActions() {
        return new Composition.NextActions();
    }

    /**
     * Create an instance of {@link Composition.Synchronization }
     * 
     */
    public Composition.Synchronization createCompositionSynchronization() {
        return new Composition.Synchronization();
    }

    /**
     * Create an instance of {@link Composition.Synchronization.Point }
     * 
     */
    public Composition.Synchronization.Point createCompositionSynchronizationPoint() {
        return new Composition.Synchronization.Point();
    }

    /**
     * Create an instance of {@link Composition.Constraints }
     * 
     */
    public Composition.Constraints createCompositionConstraints() {
        return new Composition.Constraints();
    }

    /**
     * Create an instance of {@link ClauseType }
     * 
     */
    public ClauseType createClauseType() {
        return new ClauseType();
    }

    /**
     * Create an instance of {@link ClauseType.Point }
     * 
     */
    public ClauseType.Point createClauseTypePoint() {
        return new ClauseType.Point();
    }

    /**
     * Create an instance of {@link Composition.Fragments }
     * 
     */
    public Composition.Fragments createCompositionFragments() {
        return new Composition.Fragments();
    }

    /**
     * Create an instance of {@link Composition.Fragments.Fragment }
     * 
     */
    public Composition.Fragments.Fragment createCompositionFragmentsFragment() {
        return new Composition.Fragments.Fragment();
    }

    /**
     * Create an instance of {@link Composition.DomainProperties }
     * 
     */
    public Composition.DomainProperties createCompositionDomainProperties() {
        return new Composition.DomainProperties();
    }

    /**
     * Create an instance of {@link EffectType }
     * 
     */
    public EffectType createEffectType() {
        return new EffectType();
    }

    /**
     * Create an instance of {@link eu.fbk.das.process.engine.api.jaxb.Fragment.Transition }
     * 
     */
    public eu.fbk.das.process.engine.api.jaxb.Fragment.Transition createFragmentTransition() {
        return new eu.fbk.das.process.engine.api.jaxb.Fragment.Transition();
    }

    /**
     * Create an instance of {@link OnDPchangeType }
     * 
     */
    public OnDPchangeType createOnDPchangeType() {
        return new OnDPchangeType();
    }

    /**
     * Create an instance of {@link WhileType }
     * 
     */
    public WhileType createWhileType() {
        return new WhileType();
    }

    /**
     * Create an instance of {@link PickType }
     * 
     */
    public PickType createPickType() {
        return new PickType();
    }

    /**
     * Create an instance of {@link SwitchType }
     * 
     */
    public SwitchType createSwitchType() {
        return new SwitchType();
    }

    /**
     * Create an instance of {@link SwitchType.Default }
     * 
     */
    public SwitchType.Default createSwitchTypeDefault() {
        return new SwitchType.Default();
    }

    /**
     * Create an instance of {@link SwitchType.If }
     * 
     */
    public SwitchType.If createSwitchTypeIf() {
        return new SwitchType.If();
    }

    /**
     * Create an instance of {@link DomainObject.DomainKnowledge }
     * 
     */
    public DomainObject.DomainKnowledge createDomainObjectDomainKnowledge() {
        return new DomainObject.DomainKnowledge();
    }

    /**
     * Create an instance of {@link DomainObject.State }
     * 
     */
    public DomainObject.State createDomainObjectState() {
        return new DomainObject.State();
    }

    /**
     * Create an instance of {@link DomainObject.Process }
     * 
     */
    public DomainObject.Process createDomainObjectProcess() {
        return new DomainObject.Process();
    }

    /**
     * Create an instance of {@link DomainObject.Fragment }
     * 
     */
    public DomainObject.Fragment createDomainObjectFragment() {
        return new DomainObject.Fragment();
    }

    /**
     * Create an instance of {@link eu.fbk.das.process.engine.api.jaxb.Process }
     * 
     */
    public eu.fbk.das.process.engine.api.jaxb.Process createProcess() {
        return new eu.fbk.das.process.engine.api.jaxb.Process();
    }

    /**
     * Create an instance of {@link AbstractType }
     * 
     */
    public AbstractType createAbstractType() {
        return new AbstractType();
    }

    /**
     * Create an instance of {@link ConcreteType }
     * 
     */
    public ConcreteType createConcreteType() {
        return new ConcreteType();
    }

    /**
     * Create an instance of {@link ReceiveType }
     * 
     */
    public ReceiveType createReceiveType() {
        return new ReceiveType();
    }

    /**
     * Create an instance of {@link InvokeType }
     * 
     */
    public InvokeType createInvokeType() {
        return new InvokeType();
    }

    /**
     * Create an instance of {@link ScopeType }
     * 
     */
    public ScopeType createScopeType() {
        return new ScopeType();
    }

    /**
     * Create an instance of {@link eu.fbk.das.process.engine.api.jaxb.DomainProperty.State }
     * 
     */
    public eu.fbk.das.process.engine.api.jaxb.DomainProperty.State createDomainPropertyState() {
        return new eu.fbk.das.process.engine.api.jaxb.DomainProperty.State();
    }

    /**
     * Create an instance of {@link DomainPropertyEventType }
     * 
     */
    public DomainPropertyEventType createDomainPropertyEventType() {
        return new DomainPropertyEventType();
    }

    /**
     * Create an instance of {@link eu.fbk.das.process.engine.api.jaxb.DomainProperty.Transition }
     * 
     */
    public eu.fbk.das.process.engine.api.jaxb.DomainProperty.Transition createDomainPropertyTransition() {
        return new eu.fbk.das.process.engine.api.jaxb.DomainProperty.Transition();
    }

    /**
     * Create an instance of {@link EventHandlerType }
     * 
     */
    public EventHandlerType createEventHandlerType() {
        return new EventHandlerType();
    }

    /**
     * Create an instance of {@link OnExternalEventType }
     * 
     */
    public OnExternalEventType createOnExternalEventType() {
        return new OnExternalEventType();
    }

    /**
     * Create an instance of {@link DpChangeType }
     * 
     */
    public DpChangeType createDpChangeType() {
        return new DpChangeType();
    }

    /**
     * Create an instance of {@link TriggerEventType }
     * 
     */
    public TriggerEventType createTriggerEventType() {
        return new TriggerEventType();
    }

    /**
     * Create an instance of {@link DomainPropertyStateType }
     * 
     */
    public DomainPropertyStateType createDomainPropertyStateType() {
        return new DomainPropertyStateType();
    }

    /**
     * Create an instance of {@link eu.fbk.das.process.engine.api.jaxb.Fragment.State }
     * 
     */
    public eu.fbk.das.process.engine.api.jaxb.Fragment.State createFragmentState() {
        return new eu.fbk.das.process.engine.api.jaxb.Fragment.State();
    }

    /**
     * Create an instance of {@link eu.fbk.das.process.engine.api.jaxb.Fragment.Action }
     * 
     */
    public eu.fbk.das.process.engine.api.jaxb.Fragment.Action createFragmentAction() {
        return new eu.fbk.das.process.engine.api.jaxb.Fragment.Action();
    }

    /**
     * Create an instance of {@link ServiceActionType }
     * 
     */
    public ServiceActionType createServiceActionType() {
        return new ServiceActionType();
    }

    /**
     * Create an instance of {@link ServiceStateType }
     * 
     */
    public ServiceStateType createServiceStateType() {
        return new ServiceStateType();
    }

    /**
     * Create an instance of {@link AnnotationListType }
     * 
     */
    public AnnotationListType createAnnotationListType() {
        return new AnnotationListType();
    }

    /**
     * Create an instance of {@link PreconditionType }
     * 
     */
    public PreconditionType createPreconditionType() {
        return new PreconditionType();
    }

    /**
     * Create an instance of {@link GoalType }
     * 
     */
    public GoalType createGoalType() {
        return new GoalType();
    }

    /**
     * Create an instance of {@link CompensationType }
     * 
     */
    public CompensationType createCompensationType() {
        return new CompensationType();
    }

    /**
     * Create an instance of {@link VariableType }
     * 
     */
    public VariableType createVariableType() {
        return new VariableType();
    }

    /**
     * Create an instance of {@link ArrayOfString }
     * 
     */
    public ArrayOfString createArrayOfString() {
        return new ArrayOfString();
    }

    /**
     * Create an instance of {@link Composition.ControlFlowRequirements }
     * 
     */
    public Composition.ControlFlowRequirements createCompositionControlFlowRequirements() {
        return new Composition.ControlFlowRequirements();
    }

    /**
     * Create an instance of {@link ControlFlowType.Premise }
     * 
     */
    public ControlFlowType.Premise createControlFlowTypePremise() {
        return new ControlFlowType.Premise();
    }

    /**
     * Create an instance of {@link ControlFlowType.Result.And }
     * 
     */
    public ControlFlowType.Result.And createControlFlowTypeResultAnd() {
        return new ControlFlowType.Result.And();
    }

    /**
     * Create an instance of {@link ControlFlowType.Result.Then }
     * 
     */
    public ControlFlowType.Result.Then createControlFlowTypeResultThen() {
        return new ControlFlowType.Result.Then();
    }

    /**
     * Create an instance of {@link ControlFlowType.Result.Or }
     * 
     */
    public ControlFlowType.Result.Or createControlFlowTypeResultOr() {
        return new ControlFlowType.Result.Or();
    }

    /**
     * Create an instance of {@link ControlFlowType.Result.Situation.DomainProperty }
     * 
     */
    public ControlFlowType.Result.Situation.DomainProperty createControlFlowTypeResultSituationDomainProperty() {
        return new ControlFlowType.Result.Situation.DomainProperty();
    }

    /**
     * Create an instance of {@link ControlFlowType.Result.Event.Condition.DomainProperty }
     * 
     */
    public ControlFlowType.Result.Event.Condition.DomainProperty createControlFlowTypeResultEventConditionDomainProperty() {
        return new ControlFlowType.Result.Event.Condition.DomainProperty();
    }

    /**
     * Create an instance of {@link ControlFlowType.Result.Action.Condition.DomainProperty }
     * 
     */
    public ControlFlowType.Result.Action.Condition.DomainProperty createControlFlowTypeResultActionConditionDomainProperty() {
        return new ControlFlowType.Result.Action.Condition.DomainProperty();
    }

    /**
     * Create an instance of {@link ControlFlowType.Result.Trycatch.Try }
     * 
     */
    public ControlFlowType.Result.Trycatch.Try createControlFlowTypeResultTrycatchTry() {
        return new ControlFlowType.Result.Trycatch.Try();
    }

    /**
     * Create an instance of {@link ControlFlowType.Result.Trycatch.Catch.Condition }
     * 
     */
    public ControlFlowType.Result.Trycatch.Catch.Condition createControlFlowTypeResultTrycatchCatchCondition() {
        return new ControlFlowType.Result.Trycatch.Catch.Condition();
    }

    /**
     * Create an instance of {@link ControlFlowType.Result.Trycatch.Catch.Reaction }
     * 
     */
    public ControlFlowType.Result.Trycatch.Catch.Reaction createControlFlowTypeResultTrycatchCatchReaction() {
        return new ControlFlowType.Result.Trycatch.Catch.Reaction();
    }

    /**
     * Create an instance of {@link Composition.Runtime.Fragments.Fragment }
     * 
     */
    public Composition.Runtime.Fragments.Fragment createCompositionRuntimeFragmentsFragment() {
        return new Composition.Runtime.Fragments.Fragment();
    }

    /**
     * Create an instance of {@link Composition.Runtime.DomainProperties.DomainProperty }
     * 
     */
    public Composition.Runtime.DomainProperties.DomainProperty createCompositionRuntimeDomainPropertiesDomainProperty() {
        return new Composition.Runtime.DomainProperties.DomainProperty();
    }

    /**
     * Create an instance of {@link Composition.NextActions.Action }
     * 
     */
    public Composition.NextActions.Action createCompositionNextActionsAction() {
        return new Composition.NextActions.Action();
    }

    /**
     * Create an instance of {@link Composition.Synchronization.Point.DomainProperty }
     * 
     */
    public Composition.Synchronization.Point.DomainProperty createCompositionSynchronizationPointDomainProperty() {
        return new Composition.Synchronization.Point.DomainProperty();
    }

    /**
     * Create an instance of {@link Composition.Constraints.Constraint }
     * 
     */
    public Composition.Constraints.Constraint createCompositionConstraintsConstraint() {
        return new Composition.Constraints.Constraint();
    }

    /**
     * Create an instance of {@link ClauseType.Point.DomainProperty }
     * 
     */
    public ClauseType.Point.DomainProperty createClauseTypePointDomainProperty() {
        return new ClauseType.Point.DomainProperty();
    }

    /**
     * Create an instance of {@link Composition.Fragments.Fragment.Assignment }
     * 
     */
    public Composition.Fragments.Fragment.Assignment createCompositionFragmentsFragmentAssignment() {
        return new Composition.Fragments.Fragment.Assignment();
    }

    /**
     * Create an instance of {@link Composition.DomainProperties.DomainProperty }
     * 
     */
    public Composition.DomainProperties.DomainProperty createCompositionDomainPropertiesDomainProperty() {
        return new Composition.DomainProperties.DomainProperty();
    }

    /**
     * Create an instance of {@link EffectType.Event }
     * 
     */
    public EffectType.Event createEffectTypeEvent() {
        return new EffectType.Event();
    }

    /**
     * Create an instance of {@link eu.fbk.das.process.engine.api.jaxb.Fragment.Transition.Action }
     * 
     */
    public eu.fbk.das.process.engine.api.jaxb.Fragment.Transition.Action createFragmentTransitionAction() {
        return new eu.fbk.das.process.engine.api.jaxb.Fragment.Transition.Action();
    }

    /**
     * Create an instance of {@link OnDPchangeType.DomainProperty }
     * 
     */
    public OnDPchangeType.DomainProperty createOnDPchangeTypeDomainProperty() {
        return new OnDPchangeType.DomainProperty();
    }

    /**
     * Create an instance of {@link WhileType.VarCondition }
     * 
     */
    public WhileType.VarCondition createWhileTypeVarCondition() {
        return new WhileType.VarCondition();
    }

    /**
     * Create an instance of {@link PickType.OnMessage }
     * 
     */
    public PickType.OnMessage createPickTypeOnMessage() {
        return new PickType.OnMessage();
    }

    /**
     * Create an instance of {@link SwitchType.Default.Branch }
     * 
     */
    public SwitchType.Default.Branch createSwitchTypeDefaultBranch() {
        return new SwitchType.Default.Branch();
    }

    /**
     * Create an instance of {@link SwitchType.If.VarCondition }
     * 
     */
    public SwitchType.If.VarCondition createSwitchTypeIfVarCondition() {
        return new SwitchType.If.VarCondition();
    }

    /**
     * Create an instance of {@link SwitchType.If.Branch }
     * 
     */
    public SwitchType.If.Branch createSwitchTypeIfBranch() {
        return new SwitchType.If.Branch();
    }

    /**
     * Create an instance of {@link DomainObject.DomainKnowledge.InternalDomainProperty }
     * 
     */
    public DomainObject.DomainKnowledge.InternalDomainProperty createDomainObjectDomainKnowledgeInternalDomainProperty() {
        return new DomainObject.DomainKnowledge.InternalDomainProperty();
    }

    /**
     * Create an instance of {@link DomainObject.DomainKnowledge.ExternalDomainProperty }
     * 
     */
    public DomainObject.DomainKnowledge.ExternalDomainProperty createDomainObjectDomainKnowledgeExternalDomainProperty() {
        return new DomainObject.DomainKnowledge.ExternalDomainProperty();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AnnotationListType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://das.fbk.eu/Annotation", name = "annotations")
    public JAXBElement<AnnotationListType> createAnnotations(AnnotationListType value) {
        return new JAXBElement<AnnotationListType>(_Annotations_QNAME, AnnotationListType.class, null, value);
    }

}
